using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TSQLGen.Annotations
{
    public class Field : System.Attribute
    {
        public String Name { get; }
        public Boolean IsAutoGenerated { get; }
        public Boolean IsPrimaryKey { get; }

        public Field(String fieldName = null)
        {
            this.Name = fieldName;
        }

        public Field(String fieldName, Boolean isPrimaryKey)
        {
            this.Name = fieldName;
            this.IsPrimaryKey = isPrimaryKey;
        }

        public Field(Boolean isPrimaryKey)
        {
            this.IsPrimaryKey = isPrimaryKey;
        }

        public Field(Boolean isPrimaryKey, Boolean isAutoGenerated)
        {
            this.IsPrimaryKey = isPrimaryKey;
            this.IsAutoGenerated = isAutoGenerated;
        }
    }
}
